### ISSUE TITLE
When will the training and testing codes come out?

### ISSUE THREAD

**Issue by jackieyung** [linfengWen98/CAP-VSTNet#1]
It's such a great method for video photorealistic style transfer. I can't be waiting for using this method to transfer my video to any favorite style. So, I'm wondering @linfengWen98 if you can put out the codes as soon as possible. Thanks a lot.

**Comment by linfengWen98** [comment]
Sorry, I've been busy. The code will be released within this month. Thank you for your interst in our work.

**Comment by linfengWen98** [comment]
The code has been released.
