### ISSUE TITLE
Are img_1.jpg and img_2.png content and style images

### ISSUE THREAD

**Issue by Lucy-IM** [linfengWen98/CAP-VSTNet#10]
Thank you for your excellent work. I would like to ask a question that  are img_1.jpg and img_2.png content and style images。respectively
/path_to_dir/img_1.jpg
/path_to_dir/img_2.png

**Comment by linfengWen98** [comment]
This is an example of how a folder can look like. When runing train.py, you need to provide two folders for params --train_content and --train_style respectively. And the two folders can be the same.

**Comment by Lucy-IM** [comment]
Nice to receive your reply. In the “This is an example of how a folder can look like. When runing train.py, you need to provide two folders for params --train_content and --train_style respectively. And the two folders can be the same.”, train_content folder and train_style folder can be exactly the same, right？

**Comment by Lucy-IM** [comment]
@linfengWen98    Nice to receive your reply. In the “This is an example of how a folder can look like. When runing train.py, you need to provide two folders for params --train_content and --train_style respectively. And the two folders can be the same.”, train_content folder and train_style folder can be exactly the same, right？

**Comment by linfengWen98** [comment]
> @linfengWen98 Nice to receive your reply. In the “This is an example of how a folder can look like. When runing train.py, you need to provide two folders for params --train_content and --train_style respectively. And the two folders can be the same.”, train_content folder and train_style folder can be exactly the same, right？

Yes. During training, two different batches of images will be selected.
