### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by RunDevelopment** [linfengWen98/CAP-VSTNet#18]
Hello! I would like to included CAP-VSTNet in an open source project, so I would like to ask whether you would consider adding a license to this project? A license will allow others and I to use your code in other projects under the conditions of your chosen license. 

---

If you want to use existing software licenses, then I would recommend:
- either [MIT](https://choosealicense.com/licenses/mit/) or [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) if you want a permissive license (= people can do pretty much anything with your code, under some conditions),
- or [CC-BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.en) if you do not want to allow commercial use.

I recommend these licenses, because they are commonly used by other research projects (e.g. [HAT](https://github.com/XPixelGroup/HAT), [SwinIR](https://github.com/JingyunLiang/SwinIR), [ESRGAN](https://github.com/xinntao/ESRGAN), [SRFormer](https://github.com/HVision-NKU/SRFormer), [VRT](https://github.com/JingyunLiang/VRT)).

**Comment by linfengWen98** [comment]
Thanks for your reminder. License has been added.

**Comment by RunDevelopment** [comment]
Thank you @linfengWen98!
