### ISSUE TITLE
Ablation Study

### ISSUE THREAD

**Issue by mariosvlachoulis** [linfengWen98/CAP-VSTNet#5]
Hi! Great work and approach. 
Is it possible to include the code for the alternative architectures used for the ablation study? Thanks!

**Comment by linfengWen98** [comment]
The code has been updated. The inverted residual is based on [Mobilenetv2](https://github.com/d-li14/mobilenetv2.pytorch/blob/master/models/imagenet/mobilenetv2.py#L70). The MLP is implemented with InvConv2d.
For other architectures, just change the hyperparameters or annotation the code.

**Comment by mariosvlachoulis** [comment]
Great. Thanks a lot!
